easyGame: RepPpl.h Hy.h Goll.h Creat.h Blue.h Barb.h LineQueue.h LineQueue.cpp Play.h easyPlayer.cpp StandingsStack.h StandingsStack.cpp RepPpl.cpp Hy.cpp Goll.cpp Creat.cpp Blue.cpp Barb.cpp RepPpl.cpp main.cpp
	g++ RepPpl.cpp Hy.cpp Goll.cpp Creat.cpp Blue.cpp LineQueue.cpp Barb.cpp easyPlayer.cpp StandingsStack.cpp main.cpp -o easyGame

Game: RepPpl.h Hy.h Goll.h Creat.h Blue.h Barb.h LineQueue.h LineQueue.cpp Play.h Play.cpp StandingsStack.h StandingsStack.cpp RepPpl.cpp Hy.cpp Goll.cpp Creat.cpp Blue.cpp Barb.cpp RepPpl.cpp main.cpp
	g++ RepPpl.cpp Hy.cpp Goll.cpp Creat.cpp Blue.cpp LineQueue.cpp Barb.cpp Play.cpp StandingsStack.cpp main.cpp -o Game
clean:
	rm -f *.o Game
	rm -f *.o easyGame


