VectorFun: VectorFun.cpp
	g++ VectorFun.cpp -o VectorFun
2DArrayCalculator: 2DArrayCalculator.cpp
	g++ 2DArrayCalculator.cpp -o 2DArrayCalculator
WarCardGame: WarCardGame.cpp
	g++ WarCardGame.cpp -o WarCardGame
clean:
	rm -f *.o VectorFun 2DArrayCalculator WarCardGame
