bub: BubbleSort.cpp
	g++ BubbleSort.cpp -o bub

sel: SelectionSort.cpp
	g++ SelectionSort.cpp -o sel

ins: insertionSort.cpp
	g++ insertionSort.cpp -o ins

qui: quickSort.cpp
	g++ quickSort.cpp -o qui

merg: mergesort.cpp
	g++ mergesort.cpp -o merg
