easyGame: ReptilePeople.h Hydra.h Gollum.h Creature.h BlueMen.h Barbarian.h LineupQueue.h LineupQueue.cpp Player.h easyPlayer.cpp StandingsStack.h StandingsStack.cpp ReptilePeople.cpp Hydra.cpp Gollum.cpp Creature.cpp BlueMen.cpp Barbarian.cpp ReptilePeople.cpp main.cpp
	g++ ReptilePeople.cpp Hydra.cpp Gollum.cpp Creature.cpp BlueMen.cpp LineupQueue.cpp Barbarian.cpp easyPlayer.cpp StandingsStack.cpp main.cpp -o easyGame

Game: ReptilePeople.h Hydra.h Gollum.h Creature.h BlueMen.h Barbarian.h LineupQueue.h LineupQueue.cpp Player.h Player.cpp StandingsStack.h StandingsStack.cpp ReptilePeople.cpp Hydra.cpp Gollum.cpp Creature.cpp BlueMen.cpp Barbarian.cpp ReptilePeople.cpp main.cpp
	g++ ReptilePeople.cpp Hydra.cpp Gollum.cpp Creature.cpp BlueMen.cpp LineupQueue.cpp Barbarian.cpp Player.cpp StandingsStack.cpp main.cpp -o Game
clean:
	rm -f *.o Game
	rm -f *.o easyGame


